"""
Test Run Repository
===================
The Repository Pattern separates database access logic from business logic.

WHY THE REPOSITORY PATTERN?
Instead of writing raw SQLAlchemy queries scattered throughout the codebase,
all database operations for `test_runs` are centralized here.

Benefits:
  - Easy to swap the database (MySQL → PostgreSQL → SQLite) without changing agents
  - Easy to test (can mock the repository)
  - Clean, readable code in agents and services

USAGE EXAMPLE:
    repo = TestRunRepository(db_session)
    run = repo.create(target_url="https://example.com")
    repo.update_status(run.id, "executing")
    results = repo.get_by_id(run.id)
"""

from sqlalchemy.orm import Session  # SQLAlchemy session type for type hints

from app.database.models import TestCaseRecord, TestRunRecord  # Our ORM models


class TestRunRepository:
    """
    Provides CRUD (Create, Read, Update, Delete) operations for test runs.

    All methods receive or use the database session (db) to execute queries.
    The session is provided by FastAPI's Depends(get_db) or by the service layer.
    """

    def __init__(self, db: Session):
        """
        Initializes the repository with a database session.

        Args:
            db: An active SQLAlchemy Session from SessionLocal()
                This session is shared for the duration of the request/operation
        """
        self.db = db  # Store session as an instance variable for use in all methods

    def create(
        self,
        run_id: str,
        target_url: str,
        environment: str = "development",
        user_id: str = None,
    ) -> TestRunRecord:
        """
        Creates a new test run record in the database.

        Args:
            run_id: The UUID for this run (pre-generated by the workflow)
            target_url: The URL being tested
            environment: Deployment environment name
            user_id: Optional — who triggered this run

        Returns:
            The created TestRunRecord ORM object
        """

        # Create a new ORM object — this does NOT save to DB yet
        record = TestRunRecord(
            id=run_id,               # Use the workflow's run_id as the DB primary key
            target_url=target_url,
            environment=environment,
            user_id=user_id,
            status="created",        # Initial status
        )

        # Add the object to the session (staged for INSERT)
        self.db.add(record)

        # Commit saves all staged changes to MySQL as an INSERT statement
        self.db.commit()

        # Refresh loads the saved record back from MySQL
        # This populates any server-side defaults (like auto-generated timestamps)
        self.db.refresh(record)

        return record

    def get_by_id(self, run_id: str) -> TestRunRecord | None:
        """
        Fetches a test run record by its ID.

        Args:
            run_id: The UUID of the test run

        Returns:
            The TestRunRecord if found, or None if not found
        """

        # session.get() looks up by primary key — more efficient than a full query
        return self.db.get(TestRunRecord, run_id)

    def get_all(self, limit: int = 50) -> list[TestRunRecord]:
        """
        Returns the most recent test run records.

        Args:
            limit: Maximum number of records to return

        Returns:
            List of TestRunRecord objects ordered by creation time (newest first)
        """

        return (
            self.db.query(TestRunRecord)               # SELECT * FROM test_runs
            .order_by(TestRunRecord.created_at.desc()) # ORDER BY created_at DESC
            .limit(limit)                              # LIMIT {limit}
            .all()                                     # Execute and return all results
        )

    def update_status(self, run_id: str, status: str) -> TestRunRecord | None:
        """
        Updates the status of a test run.

        Called by the LangGraph nodes as the workflow progresses:
          created → discovering → planning → test_generation → executing → completed

        Args:
            run_id: The UUID of the test run to update
            status: The new status string (from TestRunStatus enum values)

        Returns:
            The updated record, or None if not found
        """

        record = self.get_by_id(run_id)  # Find the record first

        if not record:
            return None  # Record not found — return None (caller handles this)

        record.status = status  # Update the status field on the Python object
        self.db.commit()        # Persist the change to MySQL (UPDATE statement)
        self.db.refresh(record) # Reload to get any updated timestamps

        return record

    def update_website_map(self, run_id: str, website_map: dict) -> None:
        """
        Stores the discovered website map in the test run record.

        Called after the discovery_node completes.

        Args:
            run_id: The UUID of the test run
            website_map: The WebsiteMap serialized as a dict (for JSON storage)
        """

        record = self.get_by_id(run_id)
        if record:
            record.website_map = website_map  # Set the JSON column
            self.db.commit()

    def update_test_plan(self, run_id: str, test_plan: dict) -> None:
        """
        Stores the test plan in the test run record.

        Called after the test_generation_node completes.

        Args:
            run_id: The UUID of the test run
            test_plan: The TestPlan serialized as a dict (for JSON storage)
        """

        record = self.get_by_id(run_id)
        if record:
            record.test_plan = test_plan  # Set the JSON column
            self.db.commit()

    def update_summary(self, run_id: str, summary: str) -> None:
        """
        Stores the final Markdown summary in the test run record.

        Called after the summary_node completes.

        Args:
            run_id: The UUID of the test run
            summary: The Markdown summary string from the Summarizer agent
        """

        record = self.get_by_id(run_id)
        if record:
            record.final_summary = summary  # Set the Text column
            record.status = "completed"     # Mark as completed
            self.db.commit()

    def save_test_case_result(
        self,
        run_id: str,
        test_case_id: str,
        status: str,
        actual_result: str,
        failure_data: dict = None,
    ) -> TestCaseRecord:
        """
        Saves the result of a single test case execution.

        Called for each test case after the executor agent runs it.

        Args:
            run_id: The parent test run's UUID
            test_case_id: The test case ID (e.g. "TC-001")
            status: "passed", "failed", or "blocked"
            actual_result: What the executor agent observed
            failure_data: Optional failure analysis data (for failed tests)

        Returns:
            The created TestCaseRecord
        """

        from datetime import datetime  # Import here to avoid circular imports at module level

        # Create the test case result record
        result_record = TestCaseRecord(
            run_id=run_id,
            test_case_id=test_case_id,
            status=status,
            actual_result=actual_result,
            failure_data=failure_data,
            completed_at=datetime.utcnow(),  # Record when it finished
        )

        self.db.add(result_record)  # Stage for INSERT
        self.db.commit()            # Save to MySQL
        self.db.refresh(result_record)

        return result_record
